/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as InstructorRouteRouteImport } from './routes/instructor/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentSyllabusRouteImport } from './routes/student/syllabus'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentGradesRouteImport } from './routes/student/grades'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as StudentAssignmentsRouteImport } from './routes/student/assignments'
import { Route as InstructorSubmissionsRouteImport } from './routes/instructor/submissions'
import { Route as InstructorProfileRouteImport } from './routes/instructor/profile'
import { Route as InstructorCalendarRouteImport } from './routes/instructor/calendar'
import { Route as InstructorMessagesRouteImport } from './routes/instructor/messages'
import { Route as InstructorGradebookRouteImport } from './routes/instructor/gradebook'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorCohortsRouteImport } from './routes/instructor/cohorts'
import { Route as InstructorAttendanceRouteImport } from './routes/instructor/attendance'
import { Route as InstructorAssignmentsRouteImport } from './routes/instructor/assignments'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminInstructorsRouteImport } from './routes/admin/instructors'
import { Route as AdminFacilitiesRouteImport } from './routes/admin/facilities'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCohortsRouteImport } from './routes/admin/cohorts'
import { Route as StudentAssignmentAssignmentIdRouteImport } from './routes/student/assignment.$assignmentId'
import { Route as InstructorStudentStudentIdRouteImport } from './routes/instructor/student.$studentId'
import { Route as InstructorAssignmentAssignmentIdRouteImport } from './routes/instructor/assignment.$assignmentId'
import { Route as AdminStudentStudentIdRouteImport } from './routes/admin/student.$studentId'
import { Route as AdminModuleModuleIdRouteImport } from './routes/admin/module.$moduleId'
import { Route as AdminInstructorInstructorIdRouteImport } from './routes/admin/instructor.$instructorId'
import { Route as AdminFacilityFacilityIdRouteImport } from './routes/admin/facility.$facilityId'
import { Route as AdminCohortCohortIdRouteImport } from './routes/admin/cohort.$cohortId'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRouteRoute = InstructorRouteRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSyllabusRoute = StudentSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRouteRoute,
} as any)
const InstructorSubmissionsRoute = InstructorSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorProfileRoute = InstructorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorCalendarRoute = InstructorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorMessagesRoute = InstructorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorGradebookRoute = InstructorGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorCohortsRoute = InstructorCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorAttendanceRoute = InstructorAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const InstructorAssignmentsRoute = InstructorAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => InstructorRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCohortsRoute = AdminCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentAssignmentAssignmentIdRoute =
  StudentAssignmentAssignmentIdRouteImport.update({
    id: '/assignment/$assignmentId',
    path: '/assignment/$assignmentId',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const InstructorStudentStudentIdRoute =
  InstructorStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const InstructorAssignmentAssignmentIdRoute =
  InstructorAssignmentAssignmentIdRouteImport.update({
    id: '/assignment/$assignmentId',
    path: '/assignment/$assignmentId',
    getParentRoute: () => InstructorRouteRoute,
  } as any)
const AdminStudentStudentIdRoute = AdminStudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModuleModuleIdRoute = AdminModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstructorInstructorIdRoute =
  AdminInstructorInstructorIdRouteImport.update({
    id: '/instructor/$instructorId',
    path: '/instructor/$instructorId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminFacilityFacilityIdRoute = AdminFacilityFacilityIdRouteImport.update({
  id: '/facility/$facilityId',
  path: '/facility/$facilityId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCohortCohortIdRoute = AdminCohortCohortIdRouteImport.update({
  id: '/cohort/$cohortId',
  path: '/cohort/$cohortId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor/assignments': typeof InstructorAssignmentsRoute
  '/instructor/attendance': typeof InstructorAttendanceRoute
  '/instructor/calendar': typeof InstructorCalendarRoute
  '/instructor/cohorts': typeof InstructorCohortsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/gradebook': typeof InstructorGradebookRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/submissions': typeof InstructorSubmissionsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/admin/cohort/$cohortId': typeof AdminCohortCohortIdRoute
  '/admin/facility/$facilityId': typeof AdminFacilityFacilityIdRoute
  '/admin/instructor/$instructorId': typeof AdminInstructorInstructorIdRoute
  '/admin/module/$moduleId': typeof AdminModuleModuleIdRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/instructor/assignment/$assignmentId': typeof InstructorAssignmentAssignmentIdRoute
  '/instructor/student/$studentId': typeof InstructorStudentStudentIdRoute
  '/student/assignment/$assignmentId': typeof StudentAssignmentAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor/assignments': typeof InstructorAssignmentsRoute
  '/instructor/attendance': typeof InstructorAttendanceRoute
  '/instructor/calendar': typeof InstructorCalendarRoute
  '/instructor/cohorts': typeof InstructorCohortsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/gradebook': typeof InstructorGradebookRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/submissions': typeof InstructorSubmissionsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/admin/cohort/$cohortId': typeof AdminCohortCohortIdRoute
  '/admin/facility/$facilityId': typeof AdminFacilityFacilityIdRoute
  '/admin/instructor/$instructorId': typeof AdminInstructorInstructorIdRoute
  '/admin/module/$moduleId': typeof AdminModuleModuleIdRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/instructor/assignment/$assignmentId': typeof InstructorAssignmentAssignmentIdRoute
  '/instructor/student/$studentId': typeof InstructorStudentStudentIdRoute
  '/student/assignment/$assignmentId': typeof StudentAssignmentAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/instructor': typeof InstructorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/instructor/assignments': typeof InstructorAssignmentsRoute
  '/instructor/attendance': typeof InstructorAttendanceRoute
  '/instructor/calendar': typeof InstructorCalendarRoute
  '/instructor/cohorts': typeof InstructorCohortsRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/gradebook': typeof InstructorGradebookRoute
  '/instructor/messages': typeof InstructorMessagesRoute
  '/instructor/profile': typeof InstructorProfileRoute
  '/instructor/submissions': typeof InstructorSubmissionsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/admin/cohort/$cohortId': typeof AdminCohortCohortIdRoute
  '/admin/facility/$facilityId': typeof AdminFacilityFacilityIdRoute
  '/admin/instructor/$instructorId': typeof AdminInstructorInstructorIdRoute
  '/admin/module/$moduleId': typeof AdminModuleModuleIdRoute
  '/admin/student/$studentId': typeof AdminStudentStudentIdRoute
  '/instructor/assignment/$assignmentId': typeof InstructorAssignmentAssignmentIdRoute
  '/instructor/student/$studentId': typeof InstructorStudentStudentIdRoute
  '/student/assignment/$assignmentId': typeof StudentAssignmentAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/instructor'
    | '/student'
    | '/admin/cohorts'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/instructors'
    | '/admin/students'
    | '/auth/login'
    | '/auth/register'
    | '/instructor/assignments'
    | '/instructor/attendance'
    | '/instructor/calendar'
    | '/instructor/cohorts'
    | '/instructor/dashboard'
    | '/instructor/gradebook'
    | '/instructor/messages'
    | '/instructor/profile'
    | '/instructor/submissions'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/messages'
    | '/student/profile'
    | '/student/syllabus'
    | '/admin/cohort/$cohortId'
    | '/admin/facility/$facilityId'
    | '/admin/instructor/$instructorId'
    | '/admin/module/$moduleId'
    | '/admin/student/$studentId'
    | '/instructor/assignment/$assignmentId'
    | '/instructor/student/$studentId'
    | '/student/assignment/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/instructor'
    | '/student'
    | '/admin/cohorts'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/instructors'
    | '/admin/students'
    | '/auth/login'
    | '/auth/register'
    | '/instructor/assignments'
    | '/instructor/attendance'
    | '/instructor/calendar'
    | '/instructor/cohorts'
    | '/instructor/dashboard'
    | '/instructor/gradebook'
    | '/instructor/messages'
    | '/instructor/profile'
    | '/instructor/submissions'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/messages'
    | '/student/profile'
    | '/student/syllabus'
    | '/admin/cohort/$cohortId'
    | '/admin/facility/$facilityId'
    | '/admin/instructor/$instructorId'
    | '/admin/module/$moduleId'
    | '/admin/student/$studentId'
    | '/instructor/assignment/$assignmentId'
    | '/instructor/student/$studentId'
    | '/student/assignment/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/instructor'
    | '/student'
    | '/admin/cohorts'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/instructors'
    | '/admin/students'
    | '/auth/login'
    | '/auth/register'
    | '/instructor/assignments'
    | '/instructor/attendance'
    | '/instructor/calendar'
    | '/instructor/cohorts'
    | '/instructor/dashboard'
    | '/instructor/gradebook'
    | '/instructor/messages'
    | '/instructor/profile'
    | '/instructor/submissions'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/messages'
    | '/student/profile'
    | '/student/syllabus'
    | '/admin/cohort/$cohortId'
    | '/admin/facility/$facilityId'
    | '/admin/instructor/$instructorId'
    | '/admin/module/$moduleId'
    | '/admin/student/$studentId'
    | '/instructor/assignment/$assignmentId'
    | '/instructor/student/$studentId'
    | '/student/assignment/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InstructorRouteRoute: typeof InstructorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/syllabus': {
      id: '/student/syllabus'
      path: '/syllabus'
      fullPath: '/student/syllabus'
      preLoaderRoute: typeof StudentSyllabusRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/submissions': {
      id: '/instructor/submissions'
      path: '/submissions'
      fullPath: '/instructor/submissions'
      preLoaderRoute: typeof InstructorSubmissionsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/profile': {
      id: '/instructor/profile'
      path: '/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof InstructorProfileRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/messages': {
      id: '/instructor/messages'
      path: '/messages'
      fullPath: '/instructor/messages'
      preLoaderRoute: typeof InstructorMessagesRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/gradebook': {
      id: '/instructor/gradebook'
      path: '/gradebook'
      fullPath: '/instructor/gradebook'
      preLoaderRoute: typeof InstructorGradebookRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/calendar': {
      id: '/instructor/calendar'
      path: '/calendar'
      fullPath: '/instructor/calendar'
      preLoaderRoute: typeof InstructorCalendarRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/cohorts': {
      id: '/instructor/cohorts'
      path: '/cohorts'
      fullPath: '/instructor/cohorts'
      preLoaderRoute: typeof InstructorCohortsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/attendance': {
      id: '/instructor/attendance'
      path: '/attendance'
      fullPath: '/instructor/attendance'
      preLoaderRoute: typeof InstructorAttendanceRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/assignments': {
      id: '/instructor/assignments'
      path: '/assignments'
      fullPath: '/instructor/assignments'
      preLoaderRoute: typeof InstructorAssignmentsRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cohorts': {
      id: '/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AdminCohortsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/assignment/$assignmentId': {
      id: '/student/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/student/assignment/$assignmentId'
      preLoaderRoute: typeof StudentAssignmentAssignmentIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/instructor/student/$studentId': {
      id: '/instructor/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/instructor/student/$studentId'
      preLoaderRoute: typeof InstructorStudentStudentIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/instructor/assignment/$assignmentId': {
      id: '/instructor/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/instructor/assignment/$assignmentId'
      preLoaderRoute: typeof InstructorAssignmentAssignmentIdRouteImport
      parentRoute: typeof InstructorRouteRoute
    }
    '/admin/student/$studentId': {
      id: '/admin/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/admin/student/$studentId'
      preLoaderRoute: typeof AdminStudentStudentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/module/$moduleId': {
      id: '/admin/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/admin/module/$moduleId'
      preLoaderRoute: typeof AdminModuleModuleIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instructor/$instructorId': {
      id: '/admin/instructor/$instructorId'
      path: '/instructor/$instructorId'
      fullPath: '/admin/instructor/$instructorId'
      preLoaderRoute: typeof AdminInstructorInstructorIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/facility/$facilityId': {
      id: '/admin/facility/$facilityId'
      path: '/facility/$facilityId'
      fullPath: '/admin/facility/$facilityId'
      preLoaderRoute: typeof AdminFacilityFacilityIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cohort/$cohortId': {
      id: '/admin/cohort/$cohortId'
      path: '/cohort/$cohortId'
      fullPath: '/admin/cohort/$cohortId'
      preLoaderRoute: typeof AdminCohortCohortIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCohortsRoute: typeof AdminCohortsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminCohortCohortIdRoute: typeof AdminCohortCohortIdRoute
  AdminFacilityFacilityIdRoute: typeof AdminFacilityFacilityIdRoute
  AdminInstructorInstructorIdRoute: typeof AdminInstructorInstructorIdRoute
  AdminModuleModuleIdRoute: typeof AdminModuleModuleIdRoute
  AdminStudentStudentIdRoute: typeof AdminStudentStudentIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCohortsRoute: AdminCohortsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminCohortCohortIdRoute: AdminCohortCohortIdRoute,
  AdminFacilityFacilityIdRoute: AdminFacilityFacilityIdRoute,
  AdminInstructorInstructorIdRoute: AdminInstructorInstructorIdRoute,
  AdminModuleModuleIdRoute: AdminModuleModuleIdRoute,
  AdminStudentStudentIdRoute: AdminStudentStudentIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface InstructorRouteRouteChildren {
  InstructorAssignmentsRoute: typeof InstructorAssignmentsRoute
  InstructorAttendanceRoute: typeof InstructorAttendanceRoute
  InstructorCalendarRoute: typeof InstructorCalendarRoute
  InstructorCohortsRoute: typeof InstructorCohortsRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorGradebookRoute: typeof InstructorGradebookRoute
  InstructorMessagesRoute: typeof InstructorMessagesRoute
  InstructorProfileRoute: typeof InstructorProfileRoute
  InstructorSubmissionsRoute: typeof InstructorSubmissionsRoute
  InstructorAssignmentAssignmentIdRoute: typeof InstructorAssignmentAssignmentIdRoute
  InstructorStudentStudentIdRoute: typeof InstructorStudentStudentIdRoute
}

const InstructorRouteRouteChildren: InstructorRouteRouteChildren = {
  InstructorAssignmentsRoute: InstructorAssignmentsRoute,
  InstructorAttendanceRoute: InstructorAttendanceRoute,
  InstructorCalendarRoute: InstructorCalendarRoute,
  InstructorCohortsRoute: InstructorCohortsRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorGradebookRoute: InstructorGradebookRoute,
  InstructorMessagesRoute: InstructorMessagesRoute,
  InstructorProfileRoute: InstructorProfileRoute,
  InstructorSubmissionsRoute: InstructorSubmissionsRoute,
  InstructorAssignmentAssignmentIdRoute: InstructorAssignmentAssignmentIdRoute,
  InstructorStudentStudentIdRoute: InstructorStudentStudentIdRoute,
}

const InstructorRouteRouteWithChildren = InstructorRouteRoute._addFileChildren(
  InstructorRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSyllabusRoute: typeof StudentSyllabusRoute
  StudentAssignmentAssignmentIdRoute: typeof StudentAssignmentAssignmentIdRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSyllabusRoute: StudentSyllabusRoute,
  StudentAssignmentAssignmentIdRoute: StudentAssignmentAssignmentIdRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InstructorRouteRoute: InstructorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
